### PR TITLE
Add simplified real life example from SHiP

### PR DESCRIPTION
**Pull request by olantwin**
RDF might be slightly simplified, once the [type of the split leafs is identified correctly](https://sft.its.cern.ch/jira/browse/ROOT-9674).

RDF version assumes an `RVec<ShipMCTrack>`, `TClonesArray` version with split branches is slightly different.

### CODE REVIEW

**Comment by olantwin** [comment]
Ups, how do I escape the template parameters properly?...

**Comment by eguiraud** [comment]
Thank you @olantwin ! This looks good to merge right?

**Comment by olantwin** [comment]
I think so. I'll try to simplify it in the future in new pull requests as e.g. above mentioned bug is fixed.

**Comment by olantwin** [comment]
Also for a future pull request I will try to figure out what this looks like with awkward-array.
Maybe we can add a column for non-ROOT solutions?

**Comment by eguiraud** [comment]
> Maybe we can add a column for non-ROOT solutions?
yes absolutely!

merging this for now, the document is a constant work in progress anyway :)

**Pull request merged**
